tpd:
  peer1Port: ${discovery.port1}
  peer2Port: ${discovery.port2}

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*'

---
spring:
  profiles: peer1
eureka:
  instance:
    hostname: eureka1
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka2:${tpd.peer2Port}/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${tpd.peer1Port}

---
spring:
  profiles: peer2
eureka:
  instance:
    hostname: eureka2
    appname: eureka-cluster
  client:
    serviceUrl:
      defaultZone: http://eureka1:${tpd.peer1Port}/eureka
    register-with-eureka: true
    fetch-registry: true
server:
  port: ${tpd.peer2Port}