server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:${discovery.port1}/eureka/
  instance:
    appname: composer

spring:
  application:
    name: composer
  cloud:
    config:
      discovery:
        enabled: true
        service-id: myconfigserver
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
